apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: warn
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "file"
    receivers:
      - name: "file"
        file:
          path: "/events/events.log"
          format: json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-cfg
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /events/events.log
      pos_file /var/log/fluentd/events.pos
      tag k8sEvents.kubernetes
      <parse>
        @type json
      </parse>
    </source>

    <match k8sEvents.kubernetes>
      @type remote_syslog
      host 192.168.72.166
      port 514
      severity info
      program '"k8sClusterEvents"'  # Removed invalid quoting
      hostname ${tag[0]}
      facility local5
      packet_size 9216
      <buffer tag>
      </buffer>
      <format>
        @type json
      </format>
      # Optional commented section, properly indented
      # <format>
      #   @type single_value
      #   message_key message
      # </format>
    </match>
